### PR TITLE
267 active orders fix

### LINKED ISSUE #267: Active Orders: Fix
1) Move parse & computation from action to getter in vuex-bitshares (now some assets cannot be accessed because they are not fetched at the time of getUser action)
2) Make sure the data displayed in `ActiveOrders` widget is identical to the one on wallet.bitshares (tip: just change `nameOrId` param to any account name in `getUser` method in Account service to test)
3) Rename `Opened` column to `Expiring` and make it display appopriate field, also display year in it
4) Right now it displays price in `Vol.` column. Should display `get` or `spend` depending if it is buy or sell order
5) Remove `/`
image
6) Make add `orderId` field to each order data (will need it to cancel order)

### PR DESCRIPTION
**Pull request by ololokiras**
#### What's this PR do?
Fix show bugs with Active Orders 
#### Where should the reviewer start?
src/views/ActiveOrders/ActiveOrdersTableItem.vue
#### How should this be manually tested?
Look to your active order
#### Any background context you want to provide?
merge after https://github.com/bitshares/vuex-bitshares/pull/64
#### What are the relevant tickets?
closes #267 
#### Screenshots (if appropriate)
image

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/branch-267-active-orders-fix
#### Questions:
May be we need some click event for change side like bitshares-ui?

### CODE REVIEW

File: src/views/ActiveOrders/ActiveOrdersTableItem.vue [hunk 1]
```diff
@@ -139,31 +137,31 @@ export default {
...
     },
     price() {
-      return getFloatCurrency(this.item.price)
+      return this.item.price
     },
     avg() {
       return ''
     },
     vol() {
-      return getFloatCurrency(this.item.vol)
```
Comment (roma219) [inline src/views/ActiveOrders/ActiveOrdersTableItem.vue]: Please take back `getFloatCurrency` and format functions (see https://github.com/bitshares/vuex-bitshares/pull/64#discussion_r241989334)

File: src/views/ActiveOrders/ActiveOrders.vue [hunk 2]
```diff
@@ -68,7 +68,7 @@ export default {
           { title: 'Get', field: 'get', align: 'left' },
           { title: 'Spend', field: 'spend', align: 'left' },
           { title: 'Filled', field: 'filled', align: 'right', expanded: true },
-          { title: 'Open', field: 'dateOpen', align: 'right' }
+          { title: 'Expiring', field: 'dateOpen', align: 'right' }
```
Comment (roma219) [inline src/views/ActiveOrders/ActiveOrders.vue]: Rename it to `dateExpiring`

**Review by roma219 — CHANGES_REQUESTED** [review]
https://github.com/bitshares/vuex-bitshares/pull/64#discussion_r241989334

**Review by roma219 — APPROVED** [review]
